version: "3.9"
volumes:
  mongodata:
services:
  mongo:
    image: mongo
    container_name: backend-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./data:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: track-trace
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret
  dbseed:
    build: ./dbseed
    depends_on:
      - mongo
  tracktrace_backend:
    build: src/
    depends_on:
      - mongo
    ports:
      - "8000:8000"
  tracktrace_frontend:
    image: docker pull ghcr.io/awt-ss22-track-trace-3/frontend:576b8e8ae14614efaf8f0748991b1915e40b2fbd
    depends_on:
      - tracktrace_backend
      - mongo
    ports:
      - "3000:80"
