version: "3.9"
volumes:
  mongodata:
services:
  #web:
  #  build: src/
  #  depends_on:
  #    - mongo
  #  container_name: backend
  #  command: uvicorn --host 0.0.0.0 --reload app.main:app
  #  volumes:
  #    - ./src/app:/app
  #  ports:
  #    - "8000:8000"
  mongo:
    image: mongo
    container_name: backend-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./data:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: track-trace
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret
  #dbseed:
  #  build: ./dbseed
  #  depends_on:
  #    - mongo
