version: "3.9"
volumes:
  mongodata:
  blockstore:
  rocksdb:
services:
  iroha:
    image: hyperledger/iroha:latest
    container_name: iroha
    ports: 
      - "50051:50051"
    volumes:
      - blockstore:/tmp/block_store
      - ./iroha_data:/opt/iroha_data
      - rocksdb:/path/to/wsv/folder
    environment:
      - KEY=keys/node0
    #entrypoint: irohad
  mongo:
    image: mongo
    container_name: backend-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: track-trace
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret
  dbseed:
    build: ./dbseed
    depends_on:
      - mongo
